### ISSUE TITLE
Empty <select> causes error: 'Cannot read textContent' of undefined

### ISSUE THREAD

**Issue by JonnyBurger** [LeaVerou/stretchy#19]
Demo: http://codepen.io/JonnyBurger/pen/Oyerxx

``` javascript
element.options[element.selectedIndex].textContent;
```

`element.selectedIndex` is -1, therefore this error happens

An empty `<select>` element is seldom visible, but the error can happen even if the `<select>` element is in a hidden container

**Comment by JonnyBurger** [comment]
Thank you for fixing this after 6 years! 😃 I completely forgot about opening this issue, but still a nice surprise!

**Comment by LeaVerou** [comment]
Better late than never 🤣
