### ISSUE TITLE
Improper usage of textarea property 'value' in the testsuite

### ISSUE THREAD

**Issue by JoshLambda** [LeaVerou/stretchy#39]
On Stretchy website [testsuite](https://leaverou.github.io/stretchy/test.html#textarea) page, `textarea` demonstrating initial value has no initial value.

Html code is:
`<textarea value="Hello there" style="height: 18px;"></textarea>`
should be
`<textarea style="height: 18px;">Hello there</textarea>`

Reference quote:

> Note: The value of a text area is the text between the <textarea> and </textarea> tags.

from page [Textarea value Property](https://www.w3schools.com/jsref/prop_textarea_value.asp) at [w3schools](https://www.w3schools.com/)

**Comment by anonyco** [comment]
Please do not cite the W3Schools. They are an unofficial and sometimes incorrect resource not endorsed by the W3C or WHATWG. Please cite MDN instead, and people will take you more seriously.

~Happy Coding!

**Comment by JoshLambda** [comment]
Thanks for the suggestion, I will keep that in mind.

**Comment by LeaVerou** [comment]
In this case, W3Schools does happen to be correct though (although in general do avoid it). Anyone up for sending a PR?

**Comment by Alexa-Green** [comment]
Working on this!
