### ISSUE TITLE
Bad size on first load

### ISSUE THREAD

**Issue by yukulele** [LeaVerou/stretchy#6]
Because of font loading

press `ctrl+F5` on project home page to see bug
http://leaverou.github.io/stretchy/ 

(tested on Win 7 / Firefox & Chrome)

**Comment by LeaVerou** [comment]
Any chance for a screenshot? It’s hard for me to reproduce as I have the fonts installed...

**Comment by yukulele** [comment]
Of course!

![capture d ecran 2015-07-28 a 13 26 25](https://cloud.githubusercontent.com/assets/347244/8930195/269274da-352c-11e5-9cb2-563fa827a990.png)

**Comment by yukulele** [comment]
Font load detection seem to not be easy
Only Chrome support font load event http://caniuse.com/#feat=font-loading

Other font load detection hack:
http://smnh.me/web-font-loading-detection-without-timers/

**Comment by LeaVerou** [comment]
Shit. Thanks for the report, I'll look into it!

**Comment by dobrud** [comment]
I've also run into the same issue. It seems like the initialisation on `DOMContentLoadad` is too early, as at this stage the fonts may not be loaded yet. The issue seems fixed for me when I rerun `Stretchy.resizeAll()` on the document `load` event.
